### ISSUE TITLE
How I can save media data when streamming as h.264*(mp4)?

### ISSUE THREAD

**Issue by hoang89yenthe** [respoke/respoke-sdk-android#1]

**Comment by jznadams** [comment]
Hi! 

We currently do not provide an API for doing media recording, but you could modify our SDK to do so. You would need to take a look at the RespokeCall class and modify it to extract the video from the WebRTC classes directly. I have not done this myself, so I am not entirely sure what would be involved. A number of other people are working on similar things, and a good place to start would be to look through the Discuss-WebRTC forums and post a question:

https://groups.google.com/forum/#!forum/discuss-webrtc

Thanks,
Jason

**Comment by hoang89yenthe** [comment]
Thanks .I did this :)
